// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIxozo151o1_p6KAP94TmEFdCSziVUDdg',
    appId: '1:594044580965:android:b923c1c54421b9f5e7028c',
    messagingSenderId: '594044580965',
    projectId: 'voltify-b637f',
    storageBucket: 'voltify-b637f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqeBuqLPV_UiG6MSrlAXlTC16pgFFSKw',
    appId: '1:594044580965:ios:2fe3d153bc2d7940e7028c',
    messagingSenderId: '594044580965',
    projectId: 'voltify-b637f',
    storageBucket: 'voltify-b637f.firebasestorage.app',
    iosBundleId: 'com.voltify.voltify',
  );
}
